# Sanity Check for this Test Repo to make sure it all tests correctly after I check in.
name: Test LeetCode Solutions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest
    
    env:
      Working_Folder: LeetCode/LeetCode

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Build the Solution
    - name: Build the solution
      run: dotnet build
      working-directory: ${{ env.Working_Folder }}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
      working-directory: ${{ env.Working_Folder }}
