# Sanity Check for this Test Repo to make sure it all tests correctly after I check in.
name: LeetCode Solutions

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest
    
    env:
      Working_Folder: LeetCode/LeetCode

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x
        
    # Restore NuGet Packages
    - name: Restore NuGet Packages
      run: dotnet restore
      working-directory: ${{ env.Working_Folder }}

    # Build the Solution
    - name: Build the Solution
      run: dotnet build
      working-directory: ${{ env.Working_Folder }}

    # Execute all unit tests in the solution
    - name: Execute Unit Tests
      run: dotnet test
      working-directory: ${{ env.Working_Folder }}
